2015-08-02 22:14:58,364 [5] ERROR Hunter [(null)] - Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
System.InvalidOperationException: Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
   в System.Data.Entity.Core.Objects.ObjectContext.VerifyRootForAdd(Boolean doAttach, String entitySetName, IEntityWrapper wrappedEntity, EntityEntry existingEntry, EntitySet& entitySet, Boolean& isNoOperation)
   в System.Data.Entity.Core.Objects.ObjectContext.AttachTo(String entitySetName, Object entity)
   в System.Data.Entity.Internal.Linq.InternalSet`1.<>c__DisplayClassa.<Attach>b__9()
   в System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   в System.Data.Entity.Internal.Linq.InternalSet`1.Attach(Object entity)
   в System.Data.Entity.DbSet`1.Attach(TEntity entity)
   в Hunter.DataAccess.Interface.Repository`1.Update(T entity) в d:\projects\bsa-2015-hunter\Hunter\Hunter.DataAccess.Interface\Pattern\Classes\Repository.cs:строка 75
   в Hunter.Services.Concrete.PoolService.UpdatePool(Pool pool) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\Concrete\PoolService.cs:строка 71
2015-08-02 22:15:36,417 [20] ERROR Hunter [(null)] - Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
System.InvalidOperationException: Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
   в System.Data.Entity.Core.Objects.ObjectContext.VerifyRootForAdd(Boolean doAttach, String entitySetName, IEntityWrapper wrappedEntity, EntityEntry existingEntry, EntitySet& entitySet, Boolean& isNoOperation)
   в System.Data.Entity.Core.Objects.ObjectContext.AttachTo(String entitySetName, Object entity)
   в System.Data.Entity.Internal.Linq.InternalSet`1.<>c__DisplayClassa.<Attach>b__9()
   в System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   в System.Data.Entity.Internal.Linq.InternalSet`1.Attach(Object entity)
   в System.Data.Entity.DbSet`1.Attach(TEntity entity)
   в Hunter.DataAccess.Interface.Repository`1.Update(T entity) в d:\projects\bsa-2015-hunter\Hunter\Hunter.DataAccess.Interface\Pattern\Classes\Repository.cs:строка 75
   в Hunter.Services.Concrete.PoolService.UpdatePool(Pool pool) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\Concrete\PoolService.cs:строка 71
2015-08-02 22:16:06,713 [20] ERROR Hunter [(null)] - Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
System.InvalidOperationException: Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
   в System.Data.Entity.Core.Objects.ObjectContext.VerifyRootForAdd(Boolean doAttach, String entitySetName, IEntityWrapper wrappedEntity, EntityEntry existingEntry, EntitySet& entitySet, Boolean& isNoOperation)
   в System.Data.Entity.Core.Objects.ObjectContext.AttachTo(String entitySetName, Object entity)
   в System.Data.Entity.Internal.Linq.InternalSet`1.<>c__DisplayClassa.<Attach>b__9()
   в System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   в System.Data.Entity.Internal.Linq.InternalSet`1.Attach(Object entity)
   в System.Data.Entity.DbSet`1.Attach(TEntity entity)
   в Hunter.DataAccess.Interface.Repository`1.Update(T entity) в d:\projects\bsa-2015-hunter\Hunter\Hunter.DataAccess.Interface\Pattern\Classes\Repository.cs:строка 75
   в Hunter.Services.Concrete.PoolService.UpdatePool(Pool pool) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\Concrete\PoolService.cs:строка 71
2015-08-02 22:18:07,440 [20] ERROR Hunter [(null)] - Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
System.InvalidOperationException: Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
   в System.Data.Entity.Core.Objects.ObjectContext.VerifyRootForAdd(Boolean doAttach, String entitySetName, IEntityWrapper wrappedEntity, EntityEntry existingEntry, EntitySet& entitySet, Boolean& isNoOperation)
   в System.Data.Entity.Core.Objects.ObjectContext.AttachTo(String entitySetName, Object entity)
   в System.Data.Entity.Internal.Linq.InternalSet`1.<>c__DisplayClassa.<Attach>b__9()
   в System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   в System.Data.Entity.Internal.Linq.InternalSet`1.Attach(Object entity)
   в System.Data.Entity.DbSet`1.Attach(TEntity entity)
   в Hunter.DataAccess.Interface.Repository`1.Update(T entity) в d:\projects\bsa-2015-hunter\Hunter\Hunter.DataAccess.Interface\Pattern\Classes\Repository.cs:строка 75
   в Hunter.Services.Concrete.PoolService.UpdatePool(Pool pool) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\Concrete\PoolService.cs:строка 71
2015-08-02 22:19:32,271 [29] ERROR Hunter [(null)] - Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
System.InvalidOperationException: Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
   в System.Data.Entity.Core.Objects.ObjectContext.VerifyRootForAdd(Boolean doAttach, String entitySetName, IEntityWrapper wrappedEntity, EntityEntry existingEntry, EntitySet& entitySet, Boolean& isNoOperation)
   в System.Data.Entity.Core.Objects.ObjectContext.AttachTo(String entitySetName, Object entity)
   в System.Data.Entity.Internal.Linq.InternalSet`1.<>c__DisplayClassa.<Attach>b__9()
   в System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   в System.Data.Entity.Internal.Linq.InternalSet`1.Attach(Object entity)
   в System.Data.Entity.DbSet`1.Attach(TEntity entity)
   в Hunter.DataAccess.Interface.Repository`1.Update(T entity) в d:\projects\bsa-2015-hunter\Hunter\Hunter.DataAccess.Interface\Pattern\Classes\Repository.cs:строка 75
   в Hunter.Services.Concrete.PoolService.UpdatePool(Pool pool) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\Concrete\PoolService.cs:строка 71
2015-08-02 22:19:46,056 [5] ERROR Hunter [(null)] - Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
System.InvalidOperationException: Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
   в System.Data.Entity.Core.Objects.ObjectContext.VerifyRootForAdd(Boolean doAttach, String entitySetName, IEntityWrapper wrappedEntity, EntityEntry existingEntry, EntitySet& entitySet, Boolean& isNoOperation)
   в System.Data.Entity.Core.Objects.ObjectContext.AttachTo(String entitySetName, Object entity)
   в System.Data.Entity.Internal.Linq.InternalSet`1.<>c__DisplayClassa.<Attach>b__9()
   в System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   в System.Data.Entity.Internal.Linq.InternalSet`1.Attach(Object entity)
   в System.Data.Entity.DbSet`1.Attach(TEntity entity)
   в Hunter.DataAccess.Interface.Repository`1.Update(T entity) в d:\projects\bsa-2015-hunter\Hunter\Hunter.DataAccess.Interface\Pattern\Classes\Repository.cs:строка 75
   в Hunter.Services.Concrete.PoolService.UpdatePool(Pool pool) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\Concrete\PoolService.cs:строка 71
2015-08-03 16:30:40,468 [5] ERROR Hunter [(null)] - Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
System.InvalidOperationException: Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
   в System.Data.Entity.Core.Objects.ObjectContext.VerifyRootForAdd(Boolean doAttach, String entitySetName, IEntityWrapper wrappedEntity, EntityEntry existingEntry, EntitySet& entitySet, Boolean& isNoOperation)
   в System.Data.Entity.Core.Objects.ObjectContext.AttachTo(String entitySetName, Object entity)
   в System.Data.Entity.Internal.Linq.InternalSet`1.<>c__DisplayClassa.<Attach>b__9()
   в System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   в System.Data.Entity.Internal.Linq.InternalSet`1.Attach(Object entity)
   в System.Data.Entity.DbSet`1.Attach(TEntity entity)
   в Hunter.DataAccess.Interface.Repository`1.Update(T entity) в d:\projects\bsa-2015-hunter\Hunter\Hunter.DataAccess.Interface\Pattern\Classes\Repository.cs:строка 75
   в Hunter.Services.Concrete.PoolService.UpdatePool(Pool pool) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\Concrete\PoolService.cs:строка 71
2015-08-04 22:30:58,406 [15] ERROR Hunter [(null)] - Ссылка на объект не указывает на экземпляр объекта.
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Hunter.Services.DtoModels.Extentions.PoolExtentions.ToPoolViewModel(Pool pool) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\DtoModels\Extentions\PoolExtentions.cs:строка 12
   в Hunter.Services.Concrete.PoolService.GetPoolById(Int32 id) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\Concrete\PoolService.cs:строка 44
2015-08-04 22:32:12,829 [5] ERROR Hunter [(null)] - Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
System.InvalidOperationException: Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
   в System.Data.Entity.Core.Objects.ObjectContext.VerifyRootForAdd(Boolean doAttach, String entitySetName, IEntityWrapper wrappedEntity, EntityEntry existingEntry, EntitySet& entitySet, Boolean& isNoOperation)
   в System.Data.Entity.Core.Objects.ObjectContext.AttachTo(String entitySetName, Object entity)
   в System.Data.Entity.Internal.Linq.InternalSet`1.<>c__DisplayClassa.<Attach>b__9()
   в System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   в System.Data.Entity.Internal.Linq.InternalSet`1.Attach(Object entity)
   в System.Data.Entity.DbSet`1.Attach(TEntity entity)
   в Hunter.DataAccess.Interface.Repository`1.Update(T entity) в d:\projects\bsa-2015-hunter\Hunter\Hunter.DataAccess.Interface\Pattern\Classes\Repository.cs:строка 76
   в Hunter.Services.Concrete.PoolService.UpdatePool(PoolViewModel poolViewModel) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\Concrete\PoolService.cs:строка 73
2015-08-04 22:32:20,648 [5] ERROR Hunter [(null)] - Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
System.Data.Entity.Infrastructure.DbUpdateConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions. ---> System.Data.Entity.Core.OptimisticConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
   в System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.ValidateRowsAffected(Int64 rowsAffected, UpdateCommand source)
   в System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   в System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
   в System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   в System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
   в System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   в System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Hunter.DataAccess.Interface.UnitOfWork.SaveChanges() в d:\projects\bsa-2015-hunter\Hunter\Hunter.DataAccess.Interface\Pattern\Classes\UnitOfWork.cs:строка 33
   в Hunter.Services.Concrete.PoolService.UpdatePool(PoolViewModel poolViewModel) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\Concrete\PoolService.cs:строка 74
2015-08-04 22:34:55,017 [5] ERROR Hunter [(null)] - Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
System.Data.Entity.Infrastructure.DbUpdateConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions. ---> System.Data.Entity.Core.OptimisticConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
   в System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.ValidateRowsAffected(Int64 rowsAffected, UpdateCommand source)
   в System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   в System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
   в System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   в System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
   в System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   в System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Hunter.DataAccess.Interface.UnitOfWork.SaveChanges() в d:\projects\bsa-2015-hunter\Hunter\Hunter.DataAccess.Interface\Pattern\Classes\UnitOfWork.cs:строка 33
   в Hunter.Services.Concrete.PoolService.UpdatePool(PoolViewModel poolViewModel) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\Concrete\PoolService.cs:строка 74
2015-08-04 22:35:05,447 [5] ERROR Hunter [(null)] - Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
System.Data.Entity.Infrastructure.DbUpdateConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions. ---> System.Data.Entity.Core.OptimisticConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
   в System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.ValidateRowsAffected(Int64 rowsAffected, UpdateCommand source)
   в System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   в System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
   в System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   в System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
   в System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   в System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Hunter.DataAccess.Interface.UnitOfWork.SaveChanges() в d:\projects\bsa-2015-hunter\Hunter\Hunter.DataAccess.Interface\Pattern\Classes\UnitOfWork.cs:строка 33
   в Hunter.Services.Concrete.PoolService.UpdatePool(PoolViewModel poolViewModel) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\Concrete\PoolService.cs:строка 74
2015-08-04 22:36:14,950 [6] ERROR Hunter [(null)] - Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
System.Data.Entity.Infrastructure.DbUpdateConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions. ---> System.Data.Entity.Core.OptimisticConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
   в System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.ValidateRowsAffected(Int64 rowsAffected, UpdateCommand source)
   в System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   в System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
   в System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   в System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
   в System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   в System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Hunter.DataAccess.Interface.UnitOfWork.SaveChanges() в d:\projects\bsa-2015-hunter\Hunter\Hunter.DataAccess.Interface\Pattern\Classes\UnitOfWork.cs:строка 33
   в Hunter.Services.Concrete.PoolService.UpdatePool(PoolViewModel poolViewModel) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\Concrete\PoolService.cs:строка 74
2015-08-04 22:36:38,785 [11] ERROR Hunter [(null)] - Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
System.Data.Entity.Infrastructure.DbUpdateConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions. ---> System.Data.Entity.Core.OptimisticConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
   в System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.ValidateRowsAffected(Int64 rowsAffected, UpdateCommand source)
   в System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   в System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
   в System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   в System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
   в System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   в System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Hunter.DataAccess.Interface.UnitOfWork.SaveChanges() в d:\projects\bsa-2015-hunter\Hunter\Hunter.DataAccess.Interface\Pattern\Classes\UnitOfWork.cs:строка 33
   в Hunter.Services.Concrete.PoolService.UpdatePool(PoolViewModel poolViewModel) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\Concrete\PoolService.cs:строка 74
2015-08-04 22:37:15,423 [6] ERROR Hunter [(null)] - Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
System.Data.Entity.Infrastructure.DbUpdateConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions. ---> System.Data.Entity.Core.OptimisticConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
   в System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.ValidateRowsAffected(Int64 rowsAffected, UpdateCommand source)
   в System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   в System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
   в System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   в System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
   в System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   в System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Hunter.DataAccess.Interface.UnitOfWork.SaveChanges() в d:\projects\bsa-2015-hunter\Hunter\Hunter.DataAccess.Interface\Pattern\Classes\UnitOfWork.cs:строка 33
   в Hunter.Services.Concrete.PoolService.UpdatePool(PoolViewModel poolViewModel) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\Concrete\PoolService.cs:строка 74
2015-08-04 22:38:23,491 [6] ERROR Hunter [(null)] - Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
System.Data.Entity.Infrastructure.DbUpdateConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions. ---> System.Data.Entity.Core.OptimisticConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
   в System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.ValidateRowsAffected(Int64 rowsAffected, UpdateCommand source)
   в System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.<Update>b__2(UpdateTranslator ut)
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update[T](T noChangesResult, Func`2 updateFunction)
   в System.Data.Entity.Core.EntityClient.Internal.EntityAdapter.Update()
   в System.Data.Entity.Core.Objects.ObjectContext.<SaveChangesToStore>b__35()
   в System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   в System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass2a.<SaveChangesInternal>b__27()
   в System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   в System.Data.Entity.Core.Objects.ObjectContext.SaveChanges(SaveOptions options)
   в System.Data.Entity.Internal.InternalContext.SaveChanges()
   --- Конец трассировки внутреннего стека исключений ---
   в System.Data.Entity.Internal.InternalContext.SaveChanges()
   в System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   в System.Data.Entity.DbContext.SaveChanges()
   в Hunter.DataAccess.Interface.UnitOfWork.SaveChanges() в d:\projects\bsa-2015-hunter\Hunter\Hunter.DataAccess.Interface\Pattern\Classes\UnitOfWork.cs:строка 33
   в Hunter.Services.Concrete.PoolService.UpdatePool(PoolViewModel poolViewModel) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\Concrete\PoolService.cs:строка 74
2015-08-04 22:41:04,416 [5] ERROR Hunter [(null)] - Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
System.InvalidOperationException: Attaching an entity of type 'Hunter.DataAccess.Db.Pool' failed because another entity of the same type already has the same primary key value. This can happen when using the 'Attach' method or setting the state of an entity to 'Unchanged' or 'Modified' if any entities in the graph have conflicting key values. This may be because some entities are new and have not yet received database-generated key values. In this case use the 'Add' method or the 'Added' entity state to track the graph and then set the state of non-new entities to 'Unchanged' or 'Modified' as appropriate.
   в System.Data.Entity.Core.Objects.ObjectContext.VerifyRootForAdd(Boolean doAttach, String entitySetName, IEntityWrapper wrappedEntity, EntityEntry existingEntry, EntitySet& entitySet, Boolean& isNoOperation)
   в System.Data.Entity.Core.Objects.ObjectContext.AttachTo(String entitySetName, Object entity)
   в System.Data.Entity.Internal.Linq.InternalSet`1.<>c__DisplayClassa.<Attach>b__9()
   в System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   в System.Data.Entity.Internal.Linq.InternalSet`1.Attach(Object entity)
   в System.Data.Entity.DbSet`1.Attach(TEntity entity)
   в Hunter.DataAccess.Interface.Repository`1.Update(T entity) в d:\projects\bsa-2015-hunter\Hunter\Hunter.DataAccess.Interface\Pattern\Classes\Repository.cs:строка 76
   в Hunter.Services.Concrete.PoolService.UpdatePool(PoolViewModel poolViewModel) в d:\projects\bsa-2015-hunter\Hunter\Hunter.Services\Concrete\PoolService.cs:строка 73
